
maintenance: false

rateLimits:
  rpm:
    free: 10
    basic: 10
    pro: 10
    unlimited: 0
  tokens24h:
    free: 10000
    basic: 25000
    pro: 50000
    unlimited: 0

otherLimits:
  freeQueries: 10
  imagesPerMonth:
    free: 5
    basic: 100
    pro: 200
    unlimited: 0
    
models:
  basic:
    - engine: openai
      model: gpt-5-mini
      label: OpenAI GPT-5 Mini
    - engine: google
      model: gemini-flash-latest
      label: Google Gemini Flash
    - engine: groq
      model: meta-llama/llama-4-scout-17b-16e-instruct
      label: Groq Llama 4 Scout
    - engine: anthropic
      model: claude-haiku-4-5-20251001
      label: Anthropic Claude 4.5 Haiku
    - engine: deepseek
      model: deepseek-chat
      label: DeepSeek Chat
  pro:
    - engine: openai
      model: gpt-5.1
      label: OpenAI GPT-5.1
    - engine: google
      model: gemini-pro-latest
      label: Google Gemini Pro
    - engine: groq
      model: meta-llama/llama-4-maverick-17b-128e-instruct
      label: Groq Llama 4 Maverick
    - engine: anthropic
      model: claude-sonnet-4-5-20250929
      label: Anthropic Claude 4.5 Sonnet
    - engine: xai
      model: grok-4-0709
      label: xAI Grok 4
    - engine: deepseek
      model: deepseek-reasoner
      label: DeepSeek Reasoner

chat:
  conversation:
    length: 5
  attachments:
    limit: 1

image:
  model:
    engine: replicate
    model: black-forest-labs/flux-schnell
